### ISSUE TITLE
struct.error?

### ISSUE THREAD

**Issue by cryptid11** [tenthirtyone/blocktools#2]
doing "python sight.py blkxxxxx.dat" I get this after a while:

```
Traceback (most recent call last):
File "sight.py", line 25, in <module>
main()
File "sight.py", line 20, in main
parse(blockchain)
File "sight.py", line 11, in parse
block = Block(blockchain)
File "/home/rodomonte/.bitcoin/blocks/block.py", line 21, in __init__
self.magicNum = uint4(blockchain)
File "/home/rodomonte/.bitcoin/blocks/blocktools.py", line 11, in uint4
return struct.unpack('I', stream.read(4))[0]
struct.error: unpack requires a string argument of length 4
```

also outputs, doesn't show the output addresses, why?

**Comment by tenthirtyone** [comment]
It's probably erroring out because its reached the end of the file.

These tools do not parse the Script. Addresses are included in the ScriptPubKey of the output. Also, Addresses were not used until later and the beginning of the ScriptPubKey is going to tell you the op codes. 

If you decide to add that functionality that would be great

**Comment by tenthirtyone** [comment]
Added a check for a valid block header before reading the next block. If the data file ends in the middle of transaction data it will still crash out with this error.
